name: manual release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BRALE_BOT_CLI_PAT }}
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.0.0
        # overriding some of the basic behaviors to just get the changelog
        with:
          git-user-name: brale-bot
          git-user-email: dev@brale.xyz
          github-token: ${{ secrets.BRALE_BOT_CLI_PAT }}
          output-file: false
          # always do the release, even if there are no semantic commits
          skip-on-empty: false
          tag-prefix: ''
      - uses: notiz-dev/github-action-json-property@v0.2.0
        id: packageVersion
        with:
          path: 'package.json'
          prop_path: 'version'
      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BRALE_BOT_CLI_PAT }}
        with:
          tag_name: ${{ steps.packageVersion.outputs.prop }}
          release_name: ${{ steps.packageVersion.outputs.prop }}
